export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  LEGACY_DATA: "LEGACY_DATA",
  SAVE_TOO_LARGE: "SAVE_TOO_LARGE",
  BATCH_SAVE_FAILED: "BATCH_SAVE_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
